services:
  app:
    build:
      context: .
      target: dev
    image: go-ro-monster-dev:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - MONGO_URI=${MONGO_CONN}
      - DB_NAME=${DB_NAME}
      
volumes:
  mongo_data: